[package]
name = "kzg_poly_commit_exploration"
version = "0.1.0"
edition = "2024"

[dependencies]
blst = "0.3.15"
clap = { version = "4.5.41", features = ["derive"] }
dotenvy = "0.15.7"
log = "0.4.27"
num-bigint = "0.4.6"
rand = "0.9.1"
simple_logger = "5.0.0"
