[package]
name = "kzg_poly_commit_exploration"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dotenvy = "0.15.7"
log = "0.4.27"
simple_logger = "5.0.0"
